const pactTuple = [
  { name: 'maker', type: 'address' },
  { name: 'taker', type: 'address' },
  { name: 'arbiter', type: 'address' },
  { name: 'tokenMaker', type: 'address' },
  { name: 'tokenTaker', type: 'address' },
  { name: 'amountMaker', type: 'uint128' },
  { name: 'amountTaker', type: 'uint128' },
  { name: 'collateralMaker', type: 'uint128' },
  { name: 'collateralTaker', type: 'uint128' },
  { name: 'notionalUSDC', type: 'uint128' },
  { name: 'bondAmount', type: 'uint128' },
  { name: 'arbiterFeeCap', type: 'uint128' },
  { name: 'offerExpiry', type: 'uint64' },
  { name: 'performanceDeadline', type: 'uint64' },
  { name: 'disputeDeadline', type: 'uint64' },
  { name: 'createdAt', type: 'uint64' },
  { name: 'updatedAt', type: 'uint64' },
  { name: 'kind', type: 'uint8' },
  { name: 'status', type: 'uint8' },
  { name: 'blurSize', type: 'bool' },
  { name: 'termsHash', type: 'bytes32' },
  { name: 'proofHash', type: 'bytes32' },
] as const

const disputeTuple = [
  { name: 'opener', type: 'address' },
  { name: 'claim', type: 'uint8' },
  { name: 'makerBond', type: 'uint128' },
  { name: 'takerBond', type: 'uint128' },
  { name: 'openedAt', type: 'uint64' },
  { name: 'responseDeadline', type: 'uint64' },
  { name: 'arbiterDeadline', type: 'uint64' },
] as const

export const PACT_ABI = [
  { name: 'nextId', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { name: 'getPact', type: 'function', stateMutability: 'view', inputs: [{ name: 'id', type: 'uint256' }], outputs: [{ type: 'tuple', components: pactTuple }] },
  { name: 'getDispute', type: 'function', stateMutability: 'view', inputs: [{ name: 'id', type: 'uint256' }], outputs: [{ type: 'tuple', components: disputeTuple }] },
  { name: 'credits', type: 'function', stateMutability: 'view', inputs: [{ name: 'recipient', type: 'address' }, { name: 'token', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'settledCount', type: 'function', stateMutability: 'view', inputs: [{ name: 'user', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'lostDisputeCount', type: 'function', stateMutability: 'view', inputs: [{ name: 'user', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'settledNotionalUSDC', type: 'function', stateMutability: 'view', inputs: [{ name: 'user', type: 'address' }], outputs: [{ type: 'uint256' }] },
  {
    name: 'createPact', type: 'function', stateMutability: 'nonpayable', outputs: [{ name: 'id', type: 'uint256' }],
    inputs: [
      { name: 'kind', type: 'uint8' }, { name: 'taker', type: 'address' }, { name: 'arbiter', type: 'address' },
      { name: 'tokenMaker', type: 'address' }, { name: 'tokenTaker', type: 'address' },
      { name: 'amountMaker', type: 'uint128' }, { name: 'amountTaker', type: 'uint128' },
      { name: 'notionalUSDC', type: 'uint128' }, { name: 'arbiterFeeCap', type: 'uint128' },
      { name: 'offerExpiry', type: 'uint64' }, { name: 'performanceDeadline', type: 'uint64' },
      { name: 'disputeDeadline', type: 'uint64' }, { name: 'termsDocumentHash', type: 'bytes32' }, { name: 'blurSize', type: 'bool' },
    ],
  },
  {
    name: 'createPactWithPermit', type: 'function', stateMutability: 'nonpayable', outputs: [{ name: 'id', type: 'uint256' }],
    inputs: [
      { name: 'kind', type: 'uint8' }, { name: 'taker', type: 'address' }, { name: 'arbiter', type: 'address' },
      { name: 'tokenMaker', type: 'address' }, { name: 'tokenTaker', type: 'address' },
      { name: 'amountMaker', type: 'uint128' }, { name: 'amountTaker', type: 'uint128' },
      { name: 'notionalUSDC', type: 'uint128' }, { name: 'arbiterFeeCap', type: 'uint128' },
      { name: 'offerExpiry', type: 'uint64' }, { name: 'performanceDeadline', type: 'uint64' },
      { name: 'disputeDeadline', type: 'uint64' }, { name: 'termsDocumentHash', type: 'bytes32' }, { name: 'blurSize', type: 'bool' },
      { name: 'permitDeadline', type: 'uint256' }, { name: 'v', type: 'uint8' },
      { name: 'r', type: 'bytes32' }, { name: 's', type: 'bytes32' },
    ],
  },
  { name: 'acceptPact', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }, { name: 'expectedTermsHash', type: 'bytes32' }], outputs: [] },
  { name: 'acceptPactWithPermit', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }, { name: 'expectedTermsHash', type: 'bytes32' }, { name: 'permitDeadline', type: 'uint256' }, { name: 'v', type: 'uint8' }, { name: 'r', type: 'bytes32' }, { name: 's', type: 'bytes32' }], outputs: [] },
  { name: 'cancelPact', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'expireOffer', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'submitProof', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }, { name: 'proofHash', type: 'bytes32' }], outputs: [] },
  { name: 'release', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'refundAfterDeadline', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'openDispute', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'openDisputeWithPermit', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }, { name: 'permitDeadline', type: 'uint256' }, { name: 'v', type: 'uint8' }, { name: 'r', type: 'bytes32' }, { name: 's', type: 'bytes32' }], outputs: [] },
  { name: 'respondDispute', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'respondDisputeWithPermit', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }, { name: 'permitDeadline', type: 'uint256' }, { name: 'v', type: 'uint8' }, { name: 'r', type: 'bytes32' }, { name: 's', type: 'bytes32' }], outputs: [] },
  { name: 'resolveUnansweredDispute', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'ruleDispute', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }, { name: 'winner', type: 'uint8' }, { name: 'feeClaimed', type: 'uint128' }], outputs: [] },
  { name: 'arbiterTimeout', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'id', type: 'uint256' }], outputs: [] },
  { name: 'withdraw', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'token', type: 'address' }], outputs: [] },
  {
    name: 'PactCreated', type: 'event',
    inputs: [
      { name: 'id', type: 'uint256', indexed: true }, { name: 'kind', type: 'uint8', indexed: false },
      { name: 'maker', type: 'address', indexed: true }, { name: 'taker', type: 'address', indexed: true },
      { name: 'arbiter', type: 'address', indexed: false }, { name: 'tokenMaker', type: 'address', indexed: false },
      { name: 'tokenTaker', type: 'address', indexed: false }, { name: 'amountMaker', type: 'uint128', indexed: false },
      { name: 'amountTaker', type: 'uint128', indexed: false }, { name: 'notionalUSDC', type: 'uint128', indexed: false },
      { name: 'bondAmount', type: 'uint128', indexed: false }, { name: 'arbiterFeeCap', type: 'uint128', indexed: false },
      { name: 'offerExpiry', type: 'uint64', indexed: false }, { name: 'performanceDeadline', type: 'uint64', indexed: false },
      { name: 'disputeDeadline', type: 'uint64', indexed: false }, { name: 'termsHash', type: 'bytes32', indexed: false },
      { name: 'blurSize', type: 'bool', indexed: false },
    ],
  },
] as const

export const ERC20_ABI = [
  { name: 'approve', type: 'function', stateMutability: 'nonpayable', inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }] },
  { name: 'allowance', type: 'function', stateMutability: 'view', inputs: [{ name: 'owner', type: 'address' }, { name: 'spender', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'balanceOf', type: 'function', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'decimals', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint8' }] },
] as const

export const EIP2612_ABI = [
  { name: 'name', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'string' }] },
  { name: 'version', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'string' }] },
  { name: 'nonces', type: 'function', stateMutability: 'view', inputs: [{ name: 'owner', type: 'address' }], outputs: [{ type: 'uint256' }] },
  { name: 'DOMAIN_SEPARATOR', type: 'function', stateMutability: 'view', inputs: [], outputs: [{ type: 'bytes32' }] },
] as const
